### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by samudurand** [digiaonline/react-foundation#103]
Currently the react.foundation website seem down. Is there another source for the documentation ?

**Comment by hugovk** [comment]
Thanks for letting us know, we'll have a look.

In the meantime, you can find the docs' repo at https://github.com/digiaonline/react-foundation-docs or archived at https://web.archive.org/web/20190403214937/http://react.foundation/

**Comment by timrobinson33** [comment]
It looks like the domain name has expired

**Comment by hugovk** [comment]
The docs are now up at https://digia.online/react-foundation-docs/ 🚀 

Last thing to do: there's two places in the README where the link needs updating from 

https://react.foundation

to

https://digia.online/react-foundation-docs/

Also delete the reference to the archived //github.com/digiaonline/react-boilerplate

Would someone like to do that for Hacktoberfest?

**Comment by hugovk** [comment]
Fixed in https://github.com/digiaonline/react-foundation/commit/e1d68c7e3c9f00a973ecaa6cebede5e92d3d2fcb. Thanks!
