### ISSUE TITLE
'isDisabled' property on buttons does not disable the button

### ISSUE THREAD

**Issue by DanielReid** [digiaonline/react-foundation#104]
Hi, I'd expect the isDisabled property to also have semantic functionality like it does on the normal `<button>` html component instead of purely cosmetic styling as currently is the case.

### What did you do?

- added `isDisabled={true}` to a `Button`

### What did you expect to happen?

I expected the button to not call its onClick method when clicked

### What actually happened?

The method was called

### What version of this module are you using?

^0.9.6

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
<Button
          id="next-button"
          onClick={() => {console.log('hi!') }}
          isDisabled={true}
        >
          Next step
</Button>
```

**Comment by hugovk** [comment]
Thanks for the report, however we are going to archive this repo because we're no longer using or maintaining it.
