### ISSUE TITLE
XY Grid grid-x grid-margin-x and grid-margin-y

### ISSUE THREAD

**Issue by rrichgithubwork** [digiaonline/react-foundation#125]
### What did you do?
Try to implement gutter margin for both horizontal and vertical

### What did you expect to happen?
```<Grid gutters="margin" vertical> to result in => <div className="grid-x grid-margin-x grid-margin-y">```

### What actually happened?
```<div className="grid-x grid-margin-x">```
So I have to write it as:
```<Grid gutters="margin" className="grid-margin-y">```

Is this the best way to do it or is there another prop I should be using?

### What version of this module are you using?
Latest

Thanks

**Comment by hugovk** [comment]
Thanks for the report, but we are going to archive this repo because we're no longer using or maintaining it.
