### ISSUE TITLE
Reveal component

### ISSUE THREAD

**Issue by crisu83** [digiaonline/react-foundation#20]
I wrote an initial implementation of the Reveal component for a project I've been working on:
https://gist.github.com/crisu83/9f18311b4350de7a5a59b2192c5b09ee

Any comments?

**Comment by merlinpatt** [comment]
I'd very much like to see Reveal added to this package. That's the one thing missing preventing us from using it.

With your implementation, is there anyway to dynamically change the inside of the Reveal?

I don't want to have to have dozens of modals on the page waiting to be opened.

**Comment by addykim** [comment]
Any updates on this? Wanting to update the documentation and I'm currently trying to figure out to get Reveal on react-foundation's develop branch working. If things are going to change drastically soon then I'd prefer to hold off on writing the docs.

**Comment by DmitryShevtsov** [comment]
@crisu83 any updates?

**Comment by Jalle19** [comment]
This has been added
