### ISSUE TITLE
Foundation not loading (styles)

### ISSUE THREAD

**Issue by micheljanssen** [digiaonline/react-foundation#24]
### What did you do?
Installed **react-foundation** step-by-step;

1. npm install -g create-react-app
2. create-react-app test
3. cd test
4. npm install react-foundation
5. I replaced the code in App.js to the following;

```js
import React, { Component } from 'react';
import { Column, Row } from 'react-foundation';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <div className="gridgrid">
          <Row>
            <Column small={3}>
              <div>1</div>
            </Column>
            <Column small={3}>
              <div>2</div>
            </Column>
            <Column small={3}>
              <div>3</div>
            </Column>
            <Column small={3}>
              <div>4</div>
            </Column>
          </Row>
        </div>
      </div>
    );
  }
}

export default App;

```

6. npm start

### What did you expect to happen?
I expected to see a grid system with 1 row and 4 columns (as in the examle on https://react.foundation/).

### What actually happened?
When I look at the Foundation component's CSS in the browser, no CSS is applied. It looks like there's no foundation.css available. Al elements (columns) are placed under each other.

### What version of this module are you using?
0.7.0

**Comment by joevillanueva** [comment]
@micheljanssen were you able to get this going? Doesn't seem to be working for me either.

**Comment by jonyjeffry** [comment]
@micheljanssen @joevillanueva  you should use the <link> tab to include the css document

**Comment by yn5** [comment]
@jonyjeffry Could you elaborate a bit? Do I understand correctly you mean one should use an HTML `<link/>` tag to manually include Foundation's css?

Could one of the contributors maybe verify this so we can make a pull request out of this in order to clear it up in the docs? @crisu83

**Comment by dmigliorisi** [comment]
Having this same issue here. Looks like there isn't any CSS included with this package. What has everyone else been doing to import the Foundation CSS?

**Comment by onyno** [comment]
I added foundation-sites as a yarn dependency, then in my index.js 
`import 'foundation-sites/dist/css/foundation.min.css'`

**Comment by gpspake** [comment]
This library simply provides react components that generate foundation markup so you can type `<Row>` instead of `<div className="row"></div>` It expects you to include the css yourself so including styles would be outside of the scope of this project. You just need to make sure to include the foundation css separately just like you would if you weren't using this package.

**Comment by horaciocoronel** [comment]
You need to install foundation-sites npm and then add the `import 'foundation-sites/dist/css/foundation.min.css';` in index.js

**Comment by Victroll** [comment]
@horaciocoronel That just did work! I'm feeling a little bit stupid for not installing foundation-sites... :sweat:

**Comment by dorozco15** [comment]
@horaciocoronel Im having the same issue but Imported the foundation css and row and column still dont have style.

**Comment by arjabbar** [comment]
If it seems like the row and columns classes are missing it may be because the version of foundation-sites you installed doesn't have them. You could likely use the new grid classes here: https://foundation.zurb.com/sites/docs/xy-grid.html

**Comment by Sventenhaaf** [comment]
> This library simply provides react components that generate foundation markup so you can type `<Row>` instead of `<div className="row"></div>` It expects you to include the css yourself so including styles would be outside of the scope of this project. You just need to make sure to include the foundation css separately just like you would if you weren't using this package.

Maybe one could write a line about this in  [https://react.foundation/](the documentation)?

**Comment by Jalle19** [comment]
This is mentioned in the README nowadays
