### ISSUE TITLE
Styles as in react.foundation?

### ISSUE THREAD

**Issue by dragGH102** [digiaonline/react-foundation#25]
Would it be possible to include in the Github repo the **css used for each component in react.foundation**?

I believe it would come very handy to many, to have some default  styling rather than implementing each and every class manually.

Thank you

**Comment by larpo** [comment]
As mentioned also in #24, you need to include foundation styles your self (install foundation-styles from npm and import the styles).

**Comment by Jalle19** [comment]
@crisu83 maybe we should mention this in the README since it seems to be a source of confusion?

**Comment by crisu83** [comment]
@Jalle19 Agreed. We want to keep this library separate from the styles for a better separation of concerns. Some mention about this in the docs wouldn't be a bad idea.

**Comment by crisu83** [comment]
We also use CSS modules quite a lot, in fact that's the reason why we don't use Foundation that much anymore. Feel free to experiment and create a PR and we'll go from there.

**Comment by jondkinney** [comment]
@gpspake any progress on this approach since last year?

@crisu83 do you have any more details on your (seemingly preferred) approach with CSS modules?

**Comment by crisu83** [comment]
@jondkinney What we do is install `foundation-sites` using Yarn and import it in our entry `styles.css` file. This has worked well for us in the past.

**Comment by lukos** [comment]
> 
> 
> As mentioned also in #24, you need to include foundation styles your self (install foundation-styles from npm and import the styles).

@larpo It should be foundation-sites, not foundation-styles!

**Comment by Jalle19** [comment]
This has been mentioned in the README since some time now.
