### ISSUE TITLE
propTypes usage update required

### ISSUE THREAD

**Issue by PavelPolyakov** [digiaonline/react-foundation#31]
I believe we need to have another version released, which supports new versions of React

![image](https://user-images.githubusercontent.com/839290/27383712-785e7ea2-568c-11e7-878d-645547b3a861.png)

Regards,

**Comment by crisu83** [comment]
I changed this project to use use `prop-types` library. 70b1a77d705a0f238dba4102331a9ed4fb2c8933

**Comment by PavelPolyakov** [comment]
@crisu83 
you are supergreat! thank you for the fast response.

**Comment by PavelPolyakov** [comment]
@crisu83 
We can wait for the actual release soon, right? 🙌 
https://github.com/digiaonline/react-foundation/releases

**Comment by crisu83** [comment]
Sure, I just released version `0.8.0`.

**Comment by larpo** [comment]
Seems like #30 slipped in a new instance of PropTypes import from react package...

**Comment by crisu83** [comment]
I can't make a PR to fix this because I'm at the summer cottage. It would be great if you could submit a PR that fixes this issue.
