### ISSUE TITLE
Updating for X-Y grid

### ISSUE THREAD

**Issue by gpspake** [digiaonline/react-foundation#36]
Starting a conversation:
Foundation 6.4 has been released with an [all new grid and syntax](http://foundation.zurb.com/sites/docs/xy-grid.html) so I guess the components need to be updated to support the new grid - probably with continued support for the existing - now legacy - float grid as people might still want to use it.
The new components shouldn't be too difficult to add and, without promising too much, I might be interested in helping out; I just don't want to encroach on any work someone else is already doing to that end.

**Comment by crisu83** [comment]
@gpspake Good idea, but unfortunately I don't have time to work on this right now. Feel free to make a PR for this nevertheless.

**Comment by brentdodell** [comment]
👍

**Comment by gpspake** [comment]
Does anyone have any thoughts on the best way to go about this; you'd probably want to maintain an option to use the legacy grid, so do you provide some config to avoid naming conflicts? Do you prefix the components with xy?

**Comment by gpspake** [comment]
on second though, I guess there aren't any conflicts if we use [Grid and Cell](http://foundation.zurb.com/sites/docs/xy-grid.html)

```html
<div class="grid-x">
  <div class="cell">full width cell</div>
  <div class="cell">full width cell</div>
</div>
<div class="grid-x">
  <div class="small-6 cell">6 cells</div>
  <div class="small-6 cell">6 cells</div>
</div>
<div class="grid-x">
  <div class="medium-6 large-4 cell">12/6/4 cells</div>
  <div class="medium-6 large-8 cell">12/6/8 cells</div>
</div>
```

becomes:

```html
<Grid type="x">
  <Cell>full width cell</Cell>
  <Cell>full width cell</Cell>
</div>
<Grid type="x">
  <Cell small="6">6 cells</Cell>
  <Cell small="6">6 cells</Cell>
</Grid>
<Grid type="x">
  <Cell medium="6" large="4">12/6/4 cells</Cell>
  <Cell medium="6" large="8">12/6/8 cells</Cell>
</Grid>
```

Thoughts?

**Comment by iloginow** [comment]
@gpspake Obviously all that we have to do in order to support the new XY Grid is simply add 2 new components: Grid and Cell. And update the Foundation version to 6.4.0 the package.json file of course. I don't see any possible conflicts whatsoever. I'd love to use Foundation + React as a "Front End Standard" for my projects. And I think this new XY Grid is fantastic so those two components are really missing here. Did you manage to create any of those? Because I'm also interested in helping out.

**Comment by crisu83** [comment]
This has been done, thanks to @iloginow.
