### ISSUE TITLE
Trying to get Accordion component to work

### ISSUE THREAD

**Issue by dkmartin** [digiaonline/react-foundation#37]
### What did you do?
I installed react-foundation using npm.
Then in my component I imported the necessary react-foundation components.
`import { Accordion, AccordionItem, AccordionContent, AccordionTitle} from 'react-foundation'`

Then  I set up my component as shown below (there's an axios get being called in componentDidMount to set the donors state).

```
<Accordion>
	{this.state.donors.map(function(donor, i) {
		return(
			<AccordionItem key={donor.title}>
				<AccordionTitle>{donor.title}</AccordionTitle>
				<AccordionContent>
					<div dangerouslySetInnerHTML={{__html: donor.markup}} />
				</AccordionContent>
			</AccordionItem>
		);
 	})}
</Accordion>
```
### What did you expect to happen?
I expected the accordion to open and collapse when clicking the titles

### What actually happened?
Nothing happens when you click the titles. The content is never shown.

### What version of this module are you using?
Latest version

**Comment by Jalle19** [comment]
@kbrabrand maybe you can help since you added this?

**Comment by kbrabrand** [comment]
Sorry about the delay, I've been on vacation ☀️.

Yeah. This is the discussion mentioned in #30 regarding stateful vs. stateless component. When implementing I had to make a choice on whether the state should be kept by the component or should be something that the app that use the component should keep the state and pass it to the component.

The decision was to let the components be stateless and keep the state outside react-foundation. We might want to revisit this, but it involves a fair bit of logic to check for component types in relation to automagically setting click handler props on accordion panels and so forth. What do you think, @Jalle19?

**Comment by kbrabrand** [comment]
Here is an example of how we've used it in a project:

```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import autobind from 'react-autobind';

import {
  Accordion as BaseAccordion,
  AccordionItem,
  AccordionTitle,
  AccordionContent,
} from 'react-foundation';

import Text from './Text';

export default class Accordion extends Component {
  static propTypes = {
    panels: PropTypes.arrayOf(PropTypes.object).isRequired,
  }

  constructor(props) {
    super(props);
    autobind(this);
  }

  state = { openPanels: {} }

  togglePanel(id) {
    this.setState({
      openPanels: {
        ...this.state.openPanels,
        [id]: !this.state.openPanels[id],
      },
    });
  }

  render() {
    const { panels = [] } = this.props;
    const { openPanels } = this.state;

    return (
      <BaseAccordion>
        {panels.map((panel) => {
          const active = !!openPanels[panel.id];

          return (
            <AccordionItem key={panel.id} isActive={active}>
              <AccordionTitle
                onClick={() => this.togglePanel(panel.id)}
              >{panel.heading}</AccordionTitle>

              <AccordionContent isActive={active} style={{ display: active ? 'block' : 'none' }}>
                <Text text={panel.text} />
              </AccordionContent>
            </AccordionItem>
          );
        })}
      </BaseAccordion>
    );
  }
}
```

**Comment by Jalle19** [comment]
@kbrabrand I have no opinion on any of this, I'm not a front-end developer.

**Comment by crisu83** [comment]
@kbrabrand I agree with the original decision as there are far too many edge-cases to account for.
