### ISSUE TITLE
Looking for some direction for new PRs...

### ISSUE THREAD

**Issue by ebgranger** [digiaonline/react-foundation#41]
Hey Guys,

I'm looking to see what you might want help with. I think I could flesh out some examples, look into making some of your components stateless, maybe connect the examples to redux to show a prototype for the more complex "dumb" components. I'd also like to add certain syntactic/structural changes according to the linters I've been used to but I don't want to make any PRs before getting a blessing. My team is currently using a lot of this so I'd like to flesh some things out as we do.

**Comment by Jalle19** [comment]
In general we are open to any kind of contributions! Many of us are on vacation right now so the feedback loop may me a bit slow though.

**Comment by allthesignals** [comment]
Hi @ebgranger, our team at @NYCPlanning is doing the same. @andycochran is a Foundation contributor on our team as well. Which component are you looking at starting with? We'd like to get ResponsiveNavigation better documented and address things like #23.

**Comment by crisu83** [comment]
We'd like to make this library stateless because there are so many things to consider case-by-case when writing stateful components. I have been planning on removing the `ResponsiveNavigation` completely.

**Comment by allthesignals** [comment]
@crisu83 why remove it? I'm modeling my thinking about this around [React-SemanticUI integration](https://react.semantic-ui.com), where everything is a component. ResponsiveNavigation requires JS, it'd be nice to have a component for it.

**Comment by crisu83** [comment]
@allthesignals The reason to remove it would be simplicity and to make maintenance easier for us. I suspect that the needs for such components cannot be generalized enough to be a part of this library.
