### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by danielearwicker** [digiaonline/react-foundation#44]
Looking to use this awesome package in a TS project. My options are:

- forgo type checking for now (just tell TS not to check react-foundation)
- write type declarations standalone and submit to DefinitelyTyped. Future users in my situation will have to say `npm install react-foundation @types/foundation` and the declarations will have to be manually kept in sync with future changes to your API
- send you a PR to integrate the declarations. Future users will only have to say `npm install react-foundation` and TS will find them. Declarations need to be manually updated in line with API changes.
- send you a PR that ports all your components to TS :) a long shot, but I mention it because some projects where I've submitted a PR with standalone declarations, they tell me they're planning to port to TS anyway soon... Advantage is that there is no need to maintain type declarations separately from implementation code, so they're always correct.

Thoughts, or any plans in this direction?

**Comment by crisu83** [comment]
Hey, glad to hear that you like our project. As this is a library I would prefer disconnecting type definitions from the code base. Also, we use Flow in all of our projects, so that would most likely be our choice of type definition. Does this help you?

**Comment by danielearwicker** [comment]
No problem, the second option (put declarations in DefinitelyTyped) is still fairly seamless for users, so I'll go with that.

(Side note: you may be under a misapprehension about type definitions not being allowed in libraries - many libraries are written in TS and consumed by JS projects (Angular, MobX). Others have hand-written but built-in type declarations for TS, e.g. Redux, immutable.js)

**Comment by crisu83** [comment]
I know that it's totally fine to have typings in the code-base. But, as I mentioned our choice would be Flow for React-related libraries. I have actually been thinking of adding Flow definitions for this project.

**Comment by danielearwicker** [comment]
As referenced above, TS users can now get typings for this library in the standard way:

    npm install @types/react-foundation
