### ISSUE TITLE
Question about overriding enums.js

### ISSUE THREAD

**Issue by brentdodell** [digiaonline/react-foundation#45]
Hello, I'm fairly new to React (and not an expert at JS in general). Do you have any suggestions on the best way to override the built in enums that get imported into each component?

I am using the scss version of foundation-sites, and I've made some modifications to the settings file. I've added new colors to the foundation-palette (what controls the colors for components...`primary`, `secondary`, `warning`, etc) is one change that comes to mind, but there are probably others as well.

How would I make these usable with react-foundation? In the colors example, I now have a class called `hollow` that I would need to be available in `ButtonColors`, and in `LabelColors` for sure.

**Comment by crisu83** [comment]
There is no need to override the enumerables for this. All of these modifiers are already supported. For hollow you can use the `isHollow` property. If you want to define custom classes you can use the `className` property. There is even a property for omitting the default class.
