### ISSUE TITLE
Update component examples on https://react.foundation/

### ISSUE THREAD

**Issue by brentdodell** [digiaonline/react-foundation#50]
### What did you do?
Looked for examples of Accordion & XY-Grid on https://react.foundation/

### What did you expect to happen?
I expected there to be examples for every component provided in react-foundation

### What actually happened?
Those two components (and possibly others) were missing examples.

**Comment by hdpinto** [comment]
Reveal seems to be missing documentation entirely as well

**Comment by hugovk** [comment]
Pull requests to https://github.com/digiaonline/react-foundation-docs are welcome!
