### ISSUE TITLE
Switch (react-foundation) & Switch (react-router-dom)

### ISSUE THREAD

**Issue by rodolph66** [digiaonline/react-foundation#52]
Actually I was just about to install and use the react-foundation module when I realized the availability of the <Switch /> component which is identical to <Switch>...</Switch> that I use regularly with react router v4, and I was wondering before amending any of my react code if this will be an issue...? 
Has anyone tried using both in the same component?

**Comment by nilshartmann** [comment]
I think that shouldn't be a problem. 

If you want to use both components in the same file you can just import them with different names.

For example you could  import `Switch` from react router as `RouterSwitch` to avoid name collision use:
```
import { Switch as RouterSwitch } from 'react-router-dom';

. . .
<RouterSwitch>
 . . .
</RouterSwitch>
```

**Comment by rodolph66** [comment]
(duhhh!!!) ... that did certainly slip my mind... Thanks a lot...
