### ISSUE TITLE
Abide, or more js lib import

### ISSUE THREAD

**Issue by Zorig** [digiaonline/react-foundation#54]
### What did you do?
I want to make abide work on form validation
### What did you expect to happen?
Form validation, How can i import other js library?
### What actually happened?
I tried to `import { Abide, Foundation } from 'react-foundation';`
### What version of this module are you using?
0.9.2
Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
code goes here
```

**Comment by crisu83** [comment]
Closing because this is not an issue with our library.
