### ISSUE TITLE
do not require yarn

### ISSUE THREAD

**Issue by DanielRuf** [digiaonline/react-foundation#58]
So far `npm i` throws an error as it calls `yarn` which is not mentioned as a requirement and also many do not (yet) use yarn.

**Comment by vaaralav** [comment]
Thanks for the observation Daniel! We're using yarn in this project and [the updated contributing guidelines](https://github.com/digiaonline/react-foundation/blob/master/.github/CONTRIBUTING.md) list yarn as a requirement.

**Comment by DanielRuf** [comment]
Thanks, this is much better.
