### ISSUE TITLE
Slider, Tooltip, other JS Components

### ISSUE THREAD

**Issue by merlinpatt** [digiaonline/react-foundation#6]
Do you have plans to include Slider, Tooltip, Reveal, and the other components that require JS to create them?

**Comment by crisu83** [comment]
Yes, Slider is actually on my table right now. Stay tuned for updates.

The current game plan is to implement at least one component as an example.

**Comment by merlinpatt** [comment]
Awesome. From the code, it looks like you're rewriting the JS pieces in just React and not using `var elem = new Foundation.Slider(element, options);`?

**Comment by crisu83** [comment]
@merlinpatt are you referring to the jQuery plugins or the Angular components? It's obvious that neither is a really good match together with React.

**Comment by merlinpatt** [comment]
The jQuery plugins. That makes sense. I was working on a similar project for Foundation using Meteor's Blaze. I'd love to start helping out with this one.

**Comment by crisu83** [comment]
I think what we'll do is create the stateless components and sub-components for all the stateful components, such as modal. 

Then you can use this library seamlessly together with the jQuery library. However, I wouldn't encourage people to this approach thought, but it could maybe be used for prototyping.

This would also provide us with a perfect base for building the stateful React components.

**Comment by mbrevda** [comment]
would really love to see a dropdown component!

**Comment by LeadDreamer** [comment]
I don't have a local development environment at the moment - was hacking on codepen and codesandbox to try out - but I *do* have the Slider working as a react component (slider first; will update twoHandleSlider next), and with a redux wrapper as well.  I don't think I'm in a position to be able to branch and push/pull, but can share my codesandbox with anyone interested...
It's not an extensive change, just proper use of some es6 notation...

**Comment by LeadDreamer** [comment]
I'll note that for performance sake, I kept the slider value as a *local* state, and use Redux actions to make it available to the store... so not completely stateless

**Comment by LeadDreamer** [comment]
Well, actually, the component is technically stateless now - but still driven by foundation-slider.js, and a bit tricky attaching the plugin *after* mounting, as well as attaching the action.  Others likely can do it better.  The foundation-slider.js seems involved enough that pure react/redux could be tricky.

**Comment by Jalle19** [comment]
Reveal was added some time ago

**Comment by hugovk** [comment]
Thanks for the report, however we are going to archive this repo because we're no longer using or maintaining it.
