### ISSUE TITLE
Fix the broken README badges

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/react-foundation#65]
Some of the badges are broken, probably due to the organization rename almost a year ago

* [x] test coverage
* [x] maintainability
* [x] Scrutinizer
* [x] npm version
* [x] npm downloads

**Comment by hugovk** [comment]
NPM badges are provided by Shields.io, looks like they're having some 504 problems.

See https://github.com/badges/shields/issues/1568.

**Comment by hugovk** [comment]
NPM badges working now.

![image](https://user-images.githubusercontent.com/1324225/37298952-90a91242-262a-11e8-9e08-3ddd63d9c61b.png)
