### ISSUE TITLE
Out of Date Docs.

### ISSUE THREAD

**Issue by abroccoli** [digiaonline/react-foundation#70]
```
foundation-sites@6.4.4
react-foundation@0.9.4 
```

Hey all,

New installs of foundation-sites no longer have out of the box support for the float-grid system used by the Row and Column components. It has to be specifically enabled. This will no longer work for folks like myself making fresh codebases with the latest versions of foundation-sites and react-foundation:

```js
<Row className="display">
   <Column small={2} large={4}>4 columns</Column>
   <Column small={4} large={4}>4 columns</Column>
   <Column small={6} large={4}>4 columns</Column>
</Row>
```
Digging through the commits for react-foundation, I saw that all the work to use the XY-grid system has already been done, and this works perfectly:

```js
<Grid className="display">
     <Cell small={2} large={4}>4 columns</Cell>
     <Cell small={4} large={4}>4 columns</Cell>
     <Cell small={6} large={4}>4 columns</Cell>
</Grid>
```

Updating the docs to reflect this would save a lot of headaches for foundation newbies like myself.

Appreciate all the work you've put into this!

**Comment by hugovk** [comment]
@abroccoli Thank you for the report, please could you submit a pull request to https://github.com/digiaonline/react-foundation-docs? Thanks!

**Comment by JoshuaJWayne** [comment]
**I would also like to request an update to the Documentation as well.**  I am relatively new to working with ReactJs and have been looking for a way Foundation 6 + React.  Your Components seem like the perfect pairing to do this however I am unable to use them as the instruction is not clear to a newer react developer.  

`import React from 'react-foundation' ;`
_... use components <--- this is unclear_ 

**I was able to get some of the components working in my project by importing them individually.** 
**example:** 
`import {Button, Colors, Sizes, Badge, Cell, Grid, GridContainer} from "react-foundation";`
then they work just fine but this is not clearly documented and I feel that there may be a easier way to work with your components.

Thank you for all the work that was put into this project.

**Comment by joebentaylor** [comment]
@JoshuaJWayne isnt it supposed to be:
`import Foundation from 'react-foundation`
not:
`import React from 'react-foundation`

**Comment by zoe-gonzales** [comment]
Hi, I’ve run into some of the same issues above being new to Foundation with React. This thread has helped a lot.  Is anyone currently working on these updates? If not, could I please work on them?

**Comment by hugovk** [comment]
@zoe-gonzales No-one is currently working on this, a PR would be welcome. Thank you!
