### ISSUE TITLE
XY-Grid Cell drops FlexboxPropTypes

### ISSUE THREAD

**Issue by joey-c** [digiaonline/react-foundation#79]
Cell accepts both `GeneralPropTypes` and `FlexboxPropTypes` but only calls `generalClassNames(props)`. It does not call `flexboxClassNames(props)`.

### What did you do?
Pass `alignX='center'` or `centerAlign` to a Cell

### What did you expect to happen?
Contents of cell to be centered

### What actually happened?
Contents were not centered. Cell generated did not have any other classes.

### What version of this module are you using?
0.9.3. Foundation-sites: 0.9.5.

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```js
<Cell alignX='center'>alignX</Cell>
<Cell centerAlign>centerAlign</Cell>
```

**Comment by crisu83** [comment]
@joey-c Thanks for reporting this issue. Would you mind creating a PR to fix this issue?

**Comment by crisu83** [comment]
Nevermind, I already took care of it myself. 😄

**Comment by crisu83** [comment]
Hello @joey-c, please install the latest version, [0.9.6](https://github.com/digiaonline/react-foundation/releases/tag/v0.9.6), and it should fix your issue.
