### ISSUE TITLE
Foundation is undefined

### ISSUE THREAD

**Issue by chrisdel101** [digiaonline/react-foundation#84]
Foundation is undefined. 

```
import Foundation from 'react-foundation'
console.log(Foundation)
=> undefined
```
### What did you do?
I installed `react-foundation` using `npm  install react-foundation --save` and confirmed it is added to package json. And `node_modules`. 

```
"dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-foundation": "^0.9.6",
    "react-scripts": "2.1.3"
  },
```
Logging `react` in the same way returns a function.

### What did you expect to happen?
I expected that would be able to add a something like this and have it work.
```
<div className="button-basics-example"> 
  <Button color={Colors.SUCCESS}>Save</Button>
</div>
```
If I am using it wrong I apologize but as I perceive it, the docs suggest this this how it should be used. 
### What actually happened?
The above component renders without any styles. 
### What version of this module are you using?
0.9.6

I am using create-react-app and react `16.7`. Please advise what I could be doing incorrectly.

**Comment by joebentaylor** [comment]
Have you tried
`import {Button} from 'foundation';`

**Comment by Jalle19** [comment]
As you can see in https://github.com/digiaonline/react-foundation/blob/master/src/index.js, `react-foundation` exports each component separately, so instead of `import Foundation from 'react-foundation'` you should import the components you need, e.g.:

```javascript
import {
  Breakpoints,
  Colors,
  Sizes,
  Grid,
  Cell,
  Link,
  ButtonGroup,
} from 'react-foundation';
```
